export const assets = [
  "Agile",
  "Assassin leader",
  "Bodyguards",
  "table_books",
  "table_buidings",
  "Building access",
  "Card shark",
  "Charming",
  "Contortionist",
  "Cooks books",
  "Cult leader",
  "Demigod",
  "Disciples",
  "Disguises",
  "Dungeon access",
  "Elite archer",
  "Elite fighter",
  "Erases evidence",
  "Excellent liar",
  "Extremely rich",
  "Faction leader",
  "Faction member",
  "Famous actor",
  "Famous artist",
  "Famous cleric",
  "Famous composer",
  "Famous explorer",
  "Famous general",
  "Famous poet",
  "Fast",
  "Feared",
  "Fence",
  "Forges papers",
  "Gorgeous",
  "Hears rumors",
  "Heir to a fortune",
  "Huge family",
  "Impersonator",
  "Instructor",
  "Intimidating",
  "Knows buyers",
  "Knows shortcut",
  "Launders money",
  "Local knowledge",
  "Loremaster",
  "Loyal henchmen",
  "Master mage",
  "Mechanical expert",
  "Military leader",
  "Multilingual",
  "Natural leader",
  "Noble",
  "Nothing to lose",
  "Owed favors",
  "Owed money",
  "Owns armory",
  "Owns army",
  "Owns castle",
  "Owns factory",
  "Owns fleet",
  "Owns library",
  "Owns manor",
  "Owns press",
  "Owns relics",
  "Owns ship",
  "Owns stables",
  "Owns the guards",
  "Owns tower",
  "Owns warband",
  "Political leader",
  "table_potions",
  "Potion stockpile",
  "table_powers",
  "Powerful ex",
  "Powerful friend",
  "Powerful lover",
  "Powerful parent",
  "Powerful spouse",
  "Procures gear",
  "table_professions",
  "Religious leader",
  "Respected",
  "Saboteur",
  "Secret base",
  "Secret lab",
  "Secret weapon",
  "Sells contraband",
  "Servants",
  "Shapeshifter",
  "Smuggles goods",
  "table_spells",
  "Spy network",
  "Stage magician",
  "Stealthy",
  "Strong",
  "table_structures",
  "Trained animals",
  "Trained monsters",
  "Unbreakable",
  "War hero",
];
