export const books = [
  "Adventure novel",
  "Agriculture",
  "Almanac",
  "Anatomy",
  "Ancient history",
  "Archaeology",
  "Architecture",
  "Astrology",
  "Bestiary",
  "Biography",
  "Blackmail",
  "Botany",
  "Calendars",
  "table_cityThemes",
  "Comedic novel",
  "Commerce",
  "Condemnation",
  "Confession",
  "Conspiracies",
  "Cookbook",
  "Criminal secrets",
  "Cryptography",
  "Culture",
  "Customs",
  "Diplomacy",
  "table_disasters",
  "Divination",
  "table_domains",
  "table_dungeons",
  "Epic poems",
  "Espionage",
  "Ethics",
  "Etiquette",
  "table_factions",
  "Fashion",
  "Finance",
  "Fishing",
  "Folklore",
  "Genealogy",
  "Geography",
  "Geology",
  "Ghosts",
  "Gods",
  "Hagiography",
  "Heraldry",
  "Horror stories",
  "Hunting",
  "Husbandry",
  "Journal",
  "Language",
  "Laws",
  "Letters",
  "Libraries",
  "Logic",
  "Lost empires",
  "Lost places",
  "Love poems",
  "table_magicSchools",
  "Mathematics",
  "Medicine",
  "Modern history",
  "table_monsters",
  "Music",
  "Mystery novel",
  "Mythology",
  "Nation",
  "Navigation",
  "Oceanography",
  "Painting",
  "Planar studies",
  "Politics",
  "table_potions",
  "Prayers",
  "table_professions",
  "Propaganda",
  "Prophecies",
  "Psychology",
  "Region",
  "Religion",
  "Rhetoric",
  "Romantic novel",
  "table_roomThemes",
  "Sages",
  "Sayings",
  "Sculpture",
  "Secret societies",
  "Shipbuilding",
  "Shrines",
  "Siegecraft",
  "Songs",
  "table_spells",
  "State secrets",
  "Sword fighting",
  "Theology",
  "table_traps",
  "Treasures",
  "Utopian novel",
  "War chronicle",
  "Who’s who",
  "Witch-hunting",
];
