export const buildings = [
  "Academy",
  "Alchemist",
  "Apothecary",
  "Archive",
  "Armorer",
  "Art dealer",
  "Asylum",
  "Baker",
  "Bank",
  "Barber",
  "Bathhouse",
  "Blacksmith",
  "Bookbinder",
  "Bookseller",
  "Boyer",
  "Brewery",
  "Butcher",
  "Candlemaker",
  "Carpenter",
  "Castle",
  "Catacombs",
  "Chandler",
  "Cheesemaker",
  "Clockmaker",
  "Clothier",
  "Cobbler",
  "Courthouse",
  "Criminal den",
  "Curiosity shop",
  "Dock",
  "table_dungeons",
  "Dyer",
  "Fighting pit",
  "Fletcher",
  "Fortune teller",
  "Furrier",
  "Gallery",
  "Gambling hall",
  "Garden",
  "Gatehouse",
  "Glassworks",
  "Goldsmith",
  "Guildhall",
  "Haberdashery",
  "Hospital",
  "table_inns",
  "Jeweler",
  "Law office",
  "Leatherworks",
  "Library",
  "Locksmith",
  "Lounge",
  "Manor",
  "Marketplace",
  "Mason",
  "Menagerie",
  "Monastery",
  "Moneylender",
  "Museum",
  "Observatory",
  "Opera house",
  "Orphanage",
  "Outfitter",
  "Palace",
  "Park",
  "Physician",
  "Potter",
  "Printer",
  "Prison",
  "Restaurant",
  "Room (p. 4)",
  "Rope maker",
  "Saddler",
  "Sewers",
  "Shipyards",
  "Shrine",
  "Slaughterhouse",
  "Stables",
  "Stockyard",
  "Stonecarver",
  "Structure (p. 1)",
  "Tailor",
  "Tannery",
  "Tattooist",
  "Taxidermist",
  "Temple",
  "Theater",
  "Tobacconist",
  "Townhouse",
  "University",
  "Veterinarian",
  "Warehouse",
  "Watchtower",
  "Watermill",
  "Weapon smith",
  "Weaver",
  "Windmill",
  "Winery",
  "Wizard’s tower",
  "Workshop",
];
