export const cityEvents = [
  "table_activities",
  "Alcohol ban",
  "Art trend",
  "Assassination",
  "Beggar crowds",
  "Blessing",
  "Building collapse",
  "Carnival",
  "Conscription",
  "Consecration",
  "Construction",
  "Coronation",
  "Coup",
  "Crime wave",
  "Curfew",
  "Delegation",
  "table_delusions",
  "Demolition",
  "table_disasters",
  "Discovery",
  "Dueling trend",
  "Earthquake",
  "Election",
  "Excavation",
  "Execution",
  "Exodus",
  "table_factionWars",
  "Fashion ban",
  "Fashion trend",
  "Fasting",
  "Feasting",
  "Fire",
  "Flood",
  "Funeral",
  "Gambling ban",
  "Gang war",
  "Grain shortage",
  "Heresy",
  "Holy day",
  "House war",
  "Hysteria",
  "Iconoclasm",
  "Immigration",
  "Inquisition",
  "Insurrection",
  "Invasion",
  "Jailbreak",
  "Kidnapping",
  "Landslide",
  "Magic ban",
  "Manhunt",
  "Mass arrests",
  "Mass conversion",
  "Mass execution",
  "Mass expulsion",
  "Mass pardon",
  "Meat shortage",
  "Military parade",
  "Missionaries",
  "Mourning",
  "Mud",
  "table_mutations",
  "New invention",
  "Patrols",
  "Peace talks",
  "Pilgrims",
  "Plague",
  "Political scandal",
  "Preaching",
  "Procession",
  "Proclamation",
  "Protests",
  "Public debate",
  "Public games",
  "Public prayer",
  "Refugees",
  "Religious council",
  "Religious scandal",
  "Religious war",
  "Rioting",
  "Sacrifice",
  "Schism",
  "Serial killer",
  "Siege",
  "Sinkhole",
  "Smoke",
  "Social scandal",
  "Stench",
  "Street racing",
  "Summoning",
  "Surrender",
  "Taxation",
  "Textile shortage",
  "Tournament",
  "table_travelShifts",
  "Trial",
  "Vandalism",
  "Vermin",
  "Weapons ban",
  "Wedding",
];
