export const delusions = [
  "table_activities",
  "Always drunk",
  "Always polite",
  "Always rude",
  "Always sleepy",
  "Amnesia",
  "table_animals",
  "table_assets",
  "Aura reading",
  "Automaton",
  "Being followed",
  "Cannot count",
  "Cannot lie",
  "Cannot read",
  "Chosen one",
  "Clone",
  "Constant rage",
  "Dark vision",
  "Demonic",
  "Divine",
  "Extra limb",
  "Falls in love",
  "Famous",
  "Fears PC",
  "Fears birds",
  "Fears blood",
  "table_fearsDomain",
  "Fears fire",
  "Fears gold",
  "Fears iron",
  "Fears music",
  "Fears own hand",
  "Fears rain",
  "Fears rivers",
  "Fears sleep",
  "Fears sunlight",
  "table_fearsSymbol",
  "Fears the moon",
  "Flight",
  "Genius",
  "Gets lost",
  "table_goals",
  "Gorgeous",
  "Hates violence",
  "Healing touch",
  "Hideous",
  "Illuminati",
  "Immortal",
  "In an RPG",
  "Infamous",
  "Invisible servant",
  "Invisible",
  "Invulnerable",
  "Language switch",
  "table_liabilities",
  "table_mannerisms",
  "Medium",
  "Mind controlled",
  "Missing limb",
  "table_missions",
  "table_monsters",
  "table_monsterTraits",
  "Must dance",
  "Must lie",
  "Must obey",
  "Must shout",
  "Must skip",
  "Must steal",
  "table_npcDetails",
  "table_names",
  "table_organs",
  "Personal army",
  "table_personalities",
  "Planar traveler",
  "table_powers",
  "table_professions",
  "Prophet",
  "Reincarnated",
  "Rich",
  "Says thoughts",
  "Secret monarch",
  "Sees dead people",
  "Shapeshifter",
  "Silent",
  "table_skinTextures",
  "table_sounds",
  "Spy",
  "Super strength",
  "Talks to animals",
  "Talks to plants",
  "Telekinetic",
  "Telepathic",
  "Time traveler",
  "Vampire",
  "table_weaknesses",
  "Weather control",
  "Werewolf",
  "Whispers",
  "table_wizardNames",
  "X-ray vision",
];
