export const delveShifts = [
  "Alarm",
  "Animal sounds",
  "Apparition",
  "Awakening",
  "Battle",
  "Blessing",
  "Blood scent",
  "Ceilings moves",
  "Ceremony",
  "table_cityEvents",
  "Cleaning",
  "Cloud of flies",
  "Combat sounds",
  "Construction",
  "Crystal growth",
  "Curse",
  "Dead rise",
  "Decay scent",
  "Decreased patrols",
  "table_delusions",
  "Device activates",
  "table_delusions",
  "Doors close",
  "Doors open",
  "Draining",
  "Dungeon rotates",
  "Dungeon slides",
  "Dungeon tilts",
  "Dust cloud",
  "Earthquake",
  "table_elementFlows",
  "Eruption",
  "Excavation",
  "Faction alliance",
  "Faction truce",
  "Faction war",
  "Feast",
  "Fire",
  "Flammable gas",
  "Flooding",
  "Floors move",
  "Fog",
  "Food scent",
  "Foraging",
  "Freezing",
  "Gravel flow",
  "Hatching",
  "Hot",
  "Humid",
  "Hunt",
  "Incense",
  "Increased patrols",
  "Invasion",
  "Lava flow",
  "Leak",
  "Liquid sounds",
  "Machine sounds",
  "Manure scent",
  "Monster scent",
  "Monster sounds",
  "Mud flow",
  "Music",
  "Nesting",
  "New faction",
  "New monster",
  "New rooms",
  "Oil flow",
  "Passages close",
  "Passages open",
  "Plague",
  "Planar overlay",
  "Plants bloom",
  "Plants grow",
  "Plants wither",
  "Repairs",
  "Rift opens",
  "Room revolves",
  "Room slides",
  "Room tilts",
  "Rooms filled in",
  "Rooms rearrange",
  "Sand flow",
  "table_scents",
  "Singing",
  "Sleep",
  "Smoke",
  "table_sounds",
  "Static charge",
  "Summoning",
  "Total silence",
  "table_trapEffects",
  "Traps rearm",
  "Vermin swarm",
  "Voices",
  "Walls close in",
  "Walls move",
  "Walls widen",
  "Water flow",
  "Wind",
  "Worship",
];
