export const dungeons = [
  "Alchemy lab",
  "Animal burrow",
  "Aquarium",
  "Arboretum",
  "Archive",
  "Arena",
  "Armory",
  "Art gallery",
  "Asylum",
  "Automaton",
  "Aviary",
  "Bank",
  "Bathhouse",
  "table_buildings",
  "Bunker",
  "Casino",
  "Castle",
  "Catacombs",
  "Cathedral",
  "Cave system",
  "Cistern",
  "City",
  "Clock",
  "Corpse",
  "Court",
  "Criminal den",
  "Curiosity cabinet",
  "Dam",
  "Deathtrap",
  "Depot",
  "Dig site",
  "Dormitory",
  "Faction hideout",
  "Factory",
  "Fashion gallery",
  "Feasting hall",
  "Forge",
  "Garbage pit",
  "Gateway",
  "Guildhall",
  "Historical gallery",
  "Hospital",
  "Hotel",
  "Ice caves",
  "Insect hive",
  "Instrument",
  "Kennel",
  "Kitchen",
  "Labyrinth",
  "Larder",
  "Lava tubes",
  "Library",
  "Living dungeon",
  "Lock",
  "Mansion",
  "Marketplace",
  "Mausoleum",
  "Memorial",
  "Menagerie",
  "Mill",
  "Mine",
  "Monastery",
  "Monster gallery",
  "Monster lab",
  "Monster lair",
  "Museum",
  "Mushroom forest",
  "Nest",
  "Nursery",
  "Observatory",
  "Orrery",
  "Palace",
  "Prison",
  "Race track",
  "table_rooms",
  "Sanctum",
  "Sculpture gallery",
  "Sewer",
  "Ship",
  "Silo",
  "Slaughterhouse",
  "Stable",
  "Stronghold",
  "table_structures",
  "Summoning site",
  "Temple",
  "Testing ground",
  "Theater",
  "Theme park",
  "Tomb",
  "Tower",
  "Training complex",
  "Treasure vault",
  "Tree",
  "Warehouse",
  "Warren",
  "Waterworks",
  "Weapon gallery",
  "Wine cellar",
  "Work pit",
];
