export const ingredients = [
  "table_animals",
  "Antimony",
  "Arsenic",
  "Belladonna",
  "Bitumen",
  "Black pearl",
  "Blind eye",
  "table_books",
  "Brimstone",
  "Camphor",
  "Celandine",
  "Chalk",
  "table_clothing",
  "Cobalt",
  "Cocklebur",
  "Coffin nail",
  "Columbine",
  "Copper",
  "Corpse’s hair",
  "Crossroad dust",
  "Dandelion",
  "Deathcap",
  "Devil’s trumpet",
  "Element",
  "table_fabrics",
  "table_foods",
  "Foxglove",
  "Funeral wine",
  "Gold",
  "Grave dust",
  "Hellebore",
  "Hemlock",
  "Henbane",
  "Holly",
  "Honey",
  "Hyssop",
  "Iron",
  "Killer’s hand",
  "King’s tooth",
  "Larkspur",
  "Last breath",
  "Lead",
  "Liar’s tongue",
  "Lightning bolt",
  "Lime",
  "Lodestone",
  "Lotus",
  "Lye",
  "Mandrake",
  "table_materials",
  "Meadowsweet",
  "table_miscellaneousItems",
  "Mistletoe",
  "Monk’s vow",
  "table_monsters",
  "Moonflower",
  "Mugwort",
  "Natron",
  "Nectar",
  "Nettle",
  "Newborn’s cry",
  "Nickel",
  "Nightshade",
  "table_organs",
  "Platinum",
  "Poppy",
  "table_potions",
  "Pyre ember",
  "Queen bee",
  "Queen’s blood",
  "Quicksilver",
  "Ragwort",
  "Resin",
  "Rosemary",
  "Sage",
  "Sea water",
  "Ship’s barnacle",
  "Silver",
  "Snakeweed",
  "Soot",
  "Star-metal",
  "Stinkhorn",
  "Sugar",
  "Thief’s finger",
  "Thistle",
  "Tin",
  "Tomb flower",
  "table_tools",
  "table_treasures",
  "Valerian",
  "Verdigris",
  "Vinegar",
  "Wax",
  "table_weapons",
  "Wedding ring",
  "Widow’s tears",
  "Witch hazel",
  "Wizard’s skull",
  "Wolfsbane",
  "Wormwood",
];
