export const liabilities = [
  "Alcoholic",
  "Arthritis",
  "Bad leader",
  "Bad liar",
  "Bankrupt",
  "Beholden",
  "Blackmailed",
  "Blind",
  "Cannot count",
  "Cannot read",
  "Clumsy",
  "Condescending",
  "Coward",
  "Crippled",
  "Cursed",
  "Deaf",
  "Decadent",
  "table_delusions",
  "Disloyal followers",
  "Disobeys orders",
  "Drug addict",
  "Evil lineage",
  "Exiled",
  "Faction enemy",
  "Faints",
  "Family enemy",
  "Flirts constantly",
  "table_foodAddict",
  "Fragile",
  "Gambling addict",
  "Gets in fights",
  "Glutton",
  "Greedy",
  "Gullible",
  "Hemophilia",
  "Hideous",
  "Huge debts",
  "Insurrectionist",
  "Jealous",
  "Known con artist",
  "Known murderer",
  "Known thief",
  "Known traitor",
  "Known vandal",
  "Laughingstock",
  "Lazy",
  "Leaves evidence",
  "Loud",
  "Lowborn",
  "Many enemies",
  "Many exes",
  "Migraines",
  "Military enemy",
  "Mind-controlled",
  "Misinformed",
  "Money trail",
  "table_monsterTraits",
  "table_mutations",
  "Narcissist",
  "Needs flattery",
  "Needs medicine",
  "No rights",
  "Non-human",
  "OCD",
  "Obese",
  "Obnoxious",
  "Outcast",
  "Paranoid",
  "Pariah",
  "Party animal",
  "Political enemy",
  "Poor equipment",
  "Prison record",
  "Reckless",
  "Religious enemy",
  "Scandalous birth",
  "table_scents",
  "Secret lover",
  "Seizures",
  "Senile",
  "Softhearted",
  "table_sounds",
  "Strict routines",
  "Stupid",
  "Superstitious",
  "Surveilled",
  "Suspicious",
  "Too generous",
  "Transformed",
  "Uncool",
  "Undead",
  "Unpopular",
  "Vampire",
  "Very short",
  "Wanted",
  "War criminal",
  "Weak-willed",
  "table_weaknesses",
  "Werewolf",
  "Widely despised",
];
