export const monsters = [
  "Aboleth",
  "Air elemental",
  "Angel",
  "table_animals",
  "Animated armor",
  "Banshee",
  "Basilisk",
  "Black pudding",
  "Blink dog",
  "Brain flayer",
  "Bugbear",
  "Bulette",
  "Centaur",
  "Chimera",
  "Cockatrice",
  "Crawling claw",
  "Cyclops",
  "Darkmantle",
  "Death knight",
  "Demon",
  "Dire wolf",
  "Djinn",
  "Doppelganger",
  "Dragon",
  "Dryad",
  "Earth elemental",
  "Efreet",
  "Eye tyrant",
  "Fire elemental",
  "Gargoyle",
  "Gelatinous cube",
  "Ghost",
  "Ghoul",
  "Giant",
  "table_giantAnimals",
  "Giant centipede",
  "Giant crab",
  "Giant frog",
  "Giant scorpion",
  "Giant snake",
  "Giant spider",
  "Giant weasel",
  "Gnoll",
  "Goblin",
  "Golem",
  "Gorgon",
  "Gray ooze",
  "Griffon",
  "Hag",
  "Harpy",
  "Hell hound",
  "Hippogriff",
  "Hobgoblin",
  "Homunculus",
  "Hook horror",
  "Hydra",
  "Imp",
  "Intellect devourer",
  "Invisible stalker",
  "Kobold",
  "Kraken",
  "Lich",
  "Lizardfolk",
  "Manticore",
  "Merfolk",
  "Mimic",
  "Minotaur",
  "Mummy",
  "Myconid",
  "Naga",
  "Ochre jelly",
  "Ogre",
  "Orc",
  "Owl bear",
  "Pegasus",
  "Peryton",
  "Phase spider",
  "Piercer",
  "Purple worm",
  "Rakshasa",
  "Roc",
  "Roper",
  "Rust monster",
  "Satyr",
  "Shadow",
  "Skeleton",
  "Sphinx",
  "Stirge",
  "Succubus",
  "Tarrasque",
  "Treant",
  "Troll",
  "Tyrannosaurus",
  "Unicorn",
  "Vampire",
  "Water elemental",
  "Werewolf",
  "Wyvern",
  "Yeti",
  "Zombie",
];
