export const monsterTraits = [
  "Acid blood",
  "Amphibious",
  "Ancient",
  "table_animals",
  "Animated",
  "Asymmetrical",
  "Bloated",
  "Bloodless",
  "Brittle",
  "Burning",
  "Charged",
  "Clay-like",
  "table_colors",
  "Colossal",
  "Crystalline",
  "Decaying",
  "table_delusions",
  "table_elementSkins",
  "Elongated",
  "Ethereal",
  "Ever-young",
  "Eyeless",
  "Faceless",
  "Flaking",
  "Flammable",
  "Flexible",
  "Fluffy",
  "Foaming",
  "Fungal",
  "Fuzzy",
  "Gaseous",
  "Gelatinous",
  "Geometric",
  "Hair shedding",
  "Hairless",
  "Hairy",
  "Hardened",
  "Headless",
  "Ice-cold",
  "Illusory",
  "Iridescent",
  "Large head",
  "Legless",
  "Liquid",
  "Luminous",
  "Lumpy",
  "table_mannerisms",
  "Many arms",
  "Many eyes",
  "Many faces",
  "Many heads",
  "Many legs",
  "Many mouths",
  "Mechanical",
  "Metallic",
  "Mismatched limbs",
  "Molting",
  "Muscular",
  "table_mutations",
  "No neck",
  "One eye",
  "Ooze-form",
  "table_organs",
  "table_personalities",
  "Poisonous",
  "table_potions",
  "Powdery",
  "table_powers",
  "Pulsing",
  "Radioactive",
  "Reflective",
  "Rubbery",
  "table_scents",
  "Shadowy",
  "Sharp",
  "Short limbs",
  "Shriveled",
  "Skeletal",
  "Skin shedding",
  "Slimy",
  "Smoking",
  "Soft",
  "Sooty",
  "table_sounds",
  "Sparking",
  "Steaming",
  "Sticky",
  "Stinking",
  "Stone-like",
  "Stretchy",
  "table_tactics",
  "table_textures",
  "Tiny",
  "Translucent",
  "Tree-like",
  "Two-dimensional",
  "Venomous",
  "Vibrating",
  "Waxy",
  "table_weaknesses",
];
