export const mutations = [
  "Ages backwards",
  "Ages faster",
  "table_animalBodies",
  "table_animalEars",
  "table_animalEyes",
  "table_animalForms",
  "table_animalHeads",
  "table_animalLimbs",
  "table_animalScents",
  "table_animalSkins",
  "table_animalTails",
  "table_animalTeeth",
  "table_animalVoices",
  "Antennae",
  "Antlers",
  "Arms grow",
  "Bat wings",
  "Beak",
  "Bird wings",
  "Bleeds acid",
  "Chameleon eyes",
  "Claws",
  "table_skinColors",
  "Crystal growth",
  "Drooling",
  "Duck bill",
  "Ears grow",
  "table_elementalBloods",
  "table_elementalBodies",
  "table_elementalBreaths",
  "Emits fumes",
  "Excretes ooze",
  "Extra arms",
  "Extra eyes",
  "Extra fingers",
  "Extra heads",
  "Extra legs",
  "Eye stalks",
  "Eyes grow",
  "Fangs",
  "Feathers",
  "Feet swell",
  "Fins",
  "Fly eyes",
  "Fungal growth",
  "Gain d20 inches",
  "Gills",
  "Hair growth",
  "Hair loss",
  "Hands swell",
  "Head swells",
  "Horns",
  "Invisible head",
  "Jelly arms",
  "Legs grow",
  "Long tongue",
  "Lose d20 inches",
  "table_mannerisms",
  "table_monsterTraits",
  "table_npcDetails",
  "No eyes",
  "No nose",
  "No teeth",
  "One arm",
  "One eye",
  "One leg",
  "table_organs",
  "table_personalities",
  "Pig snout",
  "table_powers",
  "Rat tail",
  "Scales",
  "table_scents",
  "Scorpion tail",
  "Shaggy fur",
  "Shell",
  "Skin boils",
  "Skin hardens",
  "Skin pattern",
  "Skin sags",
  "Skin shedding",
  "Smoke breath",
  "Snake hair",
  "table_sounds",
  "Spines",
  "Spinnerets",
  "Suction cups",
  "Sweats blood",
  "Tentacles",
  "table_bodyTextures",
  "Totally numb",
  "Translucent skin",
  "Transparent skin",
  "Tusks",
  "Two faces",
  "Warts",
  "Webbed hands",
  "Weight doubles",
  "Weight halves",
  "Wooly",
];
