export const potions = [
  "Age",
  "All languages",
  "Alter body",
  "Alter face",
  "Alter voice",
  "table_animalForms",
  "Armor",
  "Beast-speech",
  "Bird-speech",
  "Breathlessness",
  "Claws",
  "Cold-proof",
  "Courage",
  "Cure disease",
  "Cure poison",
  "Cure wounds",
  "Dark vision",
  "Dead-speech",
  "table_delusions",
  "table_effects",
  "Elasticity",
  "table_elementalForms",
  "Extra arms",
  "False death",
  "Fear",
  "Fire form",
  "Fish-speech",
  "Flight",
  "Forgetfulness",
  "Friendship",
  "Growth",
  "Grub-speech",
  "Hate",
  "Healing",
  "Hearing",
  "Heat-proof",
  "Hunger-proof",
  "Ice form",
  "Illumination",
  "Intangibility",
  "Invisibility",
  "Invulnerability",
  "Iron stomach",
  "Jumping",
  "Lightning form",
  "Lightning-proof",
  "Love",
  "Lycanthropy",
  "Magic-proof",
  "table_mannerisms",
  "Metal-proof",
  "Might",
  "Mind reading",
  "table_monsterTraits",
  "table_mutations",
  "table_npcDetails",
  "Ooze form",
  "table_organs",
  "Paranoia",
  "table_personalities",
  "Plant-speech",
  "Poison-proof",
  "table_powers",
  "table_professions",
  "Rage",
  "Sense danger",
  "Sense direction",
  "Sense evil",
  "Sense gold",
  "Sense heat",
  "Sense illusion",
  "Sense lies",
  "Sense magic",
  "Sense undead",
  "Shrinking",
  "Sleep",
  "Sleeplessness",
  "Smoke form",
  "Sniffing",
  "Sovereign acid",
  "Sovereign glue",
  "Sovereign grease",
  "Sovereign poison",
  "Speed",
  "Spines",
  "Stinger",
  "Stone-speech",
  "Swimming",
  "Telekinesis",
  "Thought-sending",
  "Undeath",
  "Vampirism",
  "Ventriloquism",
  "Vision",
  "Wall-crawling",
  "Water-breathing",
  "Water-walking",
  "Web-slinging",
  "X-ray vision",
  "Youth",
];
