export const powers = [
  "Absorb abilities",
  "Acid aura",
  "Acid bolt",
  "Acid breath",
  "Astral projection",
  "Attract",
  "Beast control",
  "Bird control",
  "Blind",
  "Blur",
  "Burrow",
  "Chameleon skin",
  "Clairaudience",
  "Clairvoyance",
  "Clone self",
  "Create illusion",
  "Deafen",
  "Drain life",
  "Dreamwalk",
  "Earthquake",
  "Echolocation",
  "table_effects",
  "table_effectAuras",
  "table_effectBlasts",
  "table_effectBolts",
  "table_effectRays",
  "Electric aura",
  "table_elementalBreaths",
  "table_elementalControls",
  "table_elementalAuras",
  "table_elementalBlasts",
  "table_elementalBolts",
  "table_elementalRays",
  "table_elementalWalls",
  "Entangle",
  "Entomb",
  "Explode",
  "Fear aura",
  "Fire aura",
  "Fire bolt",
  "Fire breath",
  "Fire control",
  "Fire starting",
  "Fire wall",
  "Fog breath",
  "Force wall",
  "Friendship aura",
  "Gravity control",
  "Grow plants",
  "Hate aura",
  "Healing aura",
  "Hypnotism",
  "Ice aura",
  "Ice bolt",
  "Ice breath",
  "Ice wall",
  "Immovability",
  "Insect control",
  "Iron wall",
  "Laser eyes",
  "Levitation",
  "Lightning bolt",
  "Lightning breath",
  "Love aura",
  "Magnetism",
  "Memory control",
  "Mimic sounds",
  "Mind control",
  "Mold flesh",
  "Mold metal",
  "Mold stone",
  "Paralyze",
  "Paranoia aura",
  "Petrify",
  "Plane shift",
  "Plant control",
  "Poison aura",
  "Poison breath",
  "table_potions",
  "Rage aura",
  "Raise dead",
  "Remove curse",
  "Repulse",
  "Rot",
  "Shockwave",
  "Silence",
  "Sleep aura",
  "Slow enemies",
  "table_spells",
  "Spirit control",
  "Stone wall",
  "Summon",
  "Swallow whole",
  "Swap minds",
  "Teleport",
  "Time control",
  "table_travelShifts",
  "Undead control",
  "Wind control",
  "Wind wall",
];
