export const rewards = [
  "A blind eye",
  "Alcohol",
  "table_animals",
  "Armor",
  "Army",
  "Artwork",
  "table_assets",
  "Blackmail",
  "Blessing",
  "Blueprints",
  "table_buildings",
  "Business",
  "Caravel",
  "Carriage",
  "Castle",
  "Chapel",
  "Charter",
  "Companion",
  "Contract",
  "Cottage",
  "Craftsmen",
  "Cypher",
  "Delivery",
  "table_dungeons",
  "Dungeon map",
  "Endorsement",
  "Estate",
  "Expert",
  "table_factionAllies",
  "Familiar",
  "Farm",
  "Favor",
  "Fishing boat",
  "Fleet",
  "Forge",
  "Formula",
  "Galleon",
  "Gold",
  "Guide",
  "Guildhall",
  "Healing",
  "Hideout",
  "Hirelings",
  "Hounds",
  "House",
  "Influential ally",
  "table_inns",
  "Jewels",
  "Key",
  "Livestock",
  "table_locations",
  "Location map",
  "Machine",
  "Magic item",
  "Magical ally",
  "Mansion",
  "table_materials",
  "Meeting",
  "Mercenaries",
  "table_monsterAllies",
  "Noble clothing",
  "Noble title",
  "Palace",
  "Pardon",
  "Planar portal",
  "Political clout",
  "table_potions",
  "Printing press",
  "Reduced sentence",
  "Relic",
  "Religious clout",
  "Renown",
  "Revenge",
  "Rights",
  "Royal clothing",
  "Safe passage",
  "Secret",
  "Servants",
  "Shortcut",
  "Sloop",
  "Social clout",
  "table_spells",
  "Spices",
  "table_structures",
  "Temple",
  "Theater",
  "Time extension",
  "Tower",
  "Training",
  "Transformation",
  "Transport",
  "table_treasure",
  "Treasure map",
  "Vineyard",
  "Wagon",
  "Warband",
  "Warhorse",
  "table_weaknesses",
  "Wealthy clothing",
  "table_weapons",
];
