export const rooms = [
  "Alchemy room",
  "Alcohol cellar",
  "Arboretum",
  "Archery range",
  "Arena",
  "Armory",
  "Arsenal",
  "Art gallery",
  "Art studio",
  "Audience hall",
  "Aviary",
  "Ballroom",
  "Banquet hall",
  "Barracks",
  "Baths",
  "Bed chamber",
  "Brewery",
  "table_buildings",
  "Catacombs",
  "Cave",
  "Cell",
  "Chapel",
  "Chasm",
  "Church",
  "Cistern",
  "Cloakroom",
  "Concert hall",
  "Conjuring room",
  "Courtroom",
  "Courtyard",
  "Crematorium",
  "Crypt",
  "Dining room",
  "Divination room",
  "Dormitory",
  "Dressing room",
  "table_dungeons",
  "Embalming room",
  "Fighting pit",
  "Fissure",
  "Forge",
  "Fountain room",
  "Gallery",
  "Game room",
  "Garden",
  "Gatehouse",
  "Great hall",
  "Guardroom",
  "Hall",
  "Infirmary",
  "Junk room",
  "Kennel",
  "Kitchen",
  "Laboratory",
  "Lair",
  "Larder",
  "Latrine",
  "Library",
  "table_locations",
  "Lounge",
  "Map room",
  "Maze",
  "table_mechanisms",
  "Meditation room",
  "Menagerie",
  "Mess hall",
  "Mews",
  "Museum",
  "Music room",
  "Nursery",
  "Observatory",
  "Pantry",
  "Parlor",
  "Pit",
  "Poison room",
  "Pool",
  "Prison",
  "Record room",
  "Salon",
  "Scriptorium",
  "Scullery",
  "Sculpture gallery",
  "Shop",
  "Shrine",
  "Slaughterhouse",
  "Smoking room",
  "Stables",
  "Storeroom",
  "table_structures",
  "Study",
  "Tapestry room",
  "Theater",
  "Throne room",
  "Torture room",
  "Training hall",
  "Treasury",
  "Trophy room",
  "Vault",
  "Work pit",
  "Workshop",
];
