export const travelShifts = [
  "Acid rain",
  "Animal migration",
  "Anvil cloud",
  "Ash cloud",
  "Ash rain",
  "Aurora",
  "Avalanche",
  "Ball lightning",
  "Bird migration",
  "Black blizzard",
  "Blizzard",
  "Blood moon",
  "Brush fire",
  "table_cityEvents",
  "Cloudburst",
  "Cold wave",
  "Cold weather",
  "table_colorSkies",
  "table_delusions",
  "Dense fog",
  "table_disasters",
  "Downburst",
  "Drizzle",
  "Dust devil",
  "Dust storm",
  "Earthquake",
  "table_effectRains",
  "Electric storms",
  "table_elementRains",
  "Fire whirls",
  "Fireflies",
  "Firestorms",
  "Flash flood",
  "Flooding",
  "Fluffy clouds",
  "Fog",
  "table_foodRains",
  "Forest fire",
  "Freezing fog",
  "Freezing rain",
  "Grass fire",
  "Haboob",
  "Hail",
  "Hailstorm",
  "Haze",
  "Heat lightning",
  "Heatwave",
  "Heavy rain",
  "Hot weather",
  "Hot winds",
  "Humidity",
  "Hurricane",
  "Ice storm",
  "Insect swarm",
  "Landslide",
  "Lava flow",
  "Light winds",
  "Lunar eclipse",
  "Meteor shower",
  "Mirage",
  "Mist",
  "Misty rain",
  "Monsoon",
  "Mudflow",
  "Murmuration",
  "Northern lights",
  "Overcast",
  "Planet alignment",
  "Pollen cloud",
  "Pyroclastic flow",
  "Rain of fish",
  "Rain of frogs",
  "Rain of worms",
  "Rainbow",
  "Salt storm",
  "Sandstorm",
  "table_scents",
  "Showers",
  "Smog",
  "Smoke",
  "Solar eclipse",
  "table_sounds",
  "Stampede",
  "Star jelly",
  "Steam devils",
  "Strong winds",
  "Sulfur clouds",
  "Swamp lights",
  "table_tasteRains",
  "table_textureRains",
  "Thunderstorms",
  "Tornado",
  "Tremors",
  "Volcanic bombs",
  "Warm rain",
  "Warm winds",
  "Waterspouts",
  "table_weaponRains",
  "Windstorm",
  "Wispy clouds",
];
