export const treasures = [
  "Alchemical device",
  "Amulet",
  "Armor",
  "Arrows",
  "Astrolabe",
  "Belt",
  "Blackmail",
  "Blueprints",
  "table_books",
  "Bow",
  "Bowl",
  "Bracelet",
  "Business record",
  "Calligraphy",
  "Candelabra",
  "Carpet",
  "Celestial map",
  "Chalice",
  "Chandelier",
  "Clock",
  "table_clothing",
  "Codpiece",
  "Comb",
  "Compass",
  "Contract",
  "Couch",
  "Crown",
  "Crystal",
  "Dagger",
  "Deed",
  "Doll",
  "Dress",
  "Earrings",
  "Embroidery",
  "Fine china",
  "Fine liquor",
  "Furs",
  "Gaming set",
  "Gemstone",
  "Helmet",
  "table_ingredients",
  "Instrument",
  "Ivory carving",
  "Lamp",
  "Letter",
  "table_materials",
  "Medal",
  "Mirror",
  "table_monsterSkins",
  "Mosaic",
  "Mural",
  "Music box",
  "Necklace",
  "table_organs",
  "Orrery",
  "Painting",
  "Pen",
  "Perfume",
  "Pipe",
  "Planar map",
  "Porcelain figure",
  "table_potions",
  "Prayer book",
  "Printing block",
  "Rare coin",
  "Relic",
  "table_rewards",
  "Ring",
  "Royal robes",
  "Scabbard",
  "Scientific device",
  "Scrimshaw",
  "Sextant",
  "Sheet music",
  "Shield",
  "Shoes",
  "Signet ring",
  "Silk",
  "Silverware",
  "Snuffbox",
  "Spear",
  "table_spells",
  "Spices",
  "Spyglass",
  "Stained glass",
  "State secrets",
  "Stone statue",
  "Sword",
  "Table",
  "Tapestry",
  "Taxidermy",
  "Tea set",
  "Telescope",
  "Throne",
  "Treasure map",
  "Trophy",
  "Trunk",
  "Vase",
  "Watch",
  "table_weapons",
];
