export const weaknesses = [
  "Acid",
  "Alcohol",
  "table_animals",
  "Anti-magic",
  "Arms",
  "Arrows",
  "Birds",
  "Blessings",
  "Blood",
  "Blunt damage",
  "Chest",
  "Children",
  "Church bells",
  "Cold",
  "table_colors",
  "Competition",
  "Conversation",
  "Cutting damage",
  "Darkness",
  "Dirt",
  "Disease",
  "table_domains",
  "Ears",
  "table_elements",
  "Eyes",
  "Feet",
  "Fingers",
  "Fire",
  "Firelight",
  "Fish",
  "Flattery",
  "Flowers",
  "table_foods",
  "Garlic",
  "Gifts",
  "Gold",
  "Hands",
  "table_hazards",
  "Heart",
  "Heat",
  "Holy image",
  "Holy oil",
  "Holy water",
  "Ice",
  "table_ingredients",
  "Insects",
  "Insults",
  "Iron",
  "Legs",
  "Lightning",
  "table_locations",
  "Machines",
  "table_magicSchools",
  "table_materials",
  "Mirrors",
  "table_miscellaneousItems",
  "Mistletoe",
  "Moonlight",
  "Mouth",
  "Music",
  "Neck",
  "Noise",
  "Nose",
  "Oil",
  "Phylactery",
  "Piercing damage",
  "Poison",
  "table_professions",
  "Psychic damage",
  "Puzzles",
  "Rain",
  "Relic",
  "Riddles",
  "Rituals",
  "Running water",
  "Salt",
  "table_scents",
  "Seawater",
  "Silver",
  "Singing",
  "Skin",
  "Soap",
  "table_sounds",
  "table_spells",
  "Spicy food",
  "Spine",
  "Starlight",
  "Sunlight",
  "table_symbols",
  "table_tactics",
  "Tears",
  "Thunder",
  "table_tools",
  "table_travelShifts",
  "table_treasure",
  "True name",
  "Water",
  "table_weapons",
  "Wolfsbane",
  "Wormwood",
];
